#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'chef-client'
cookbook 'php5-fpm'
cookbook 'php5_ppa'
cookbook 'nginx'
cookbook 'nginx-fastcgi'
cookbook 'varnishd'
cookbook 'mariadb',
    :git => 'https://github.com/joerocklin/chef-mariadb.git'
